NEWSPAPER1/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    
    # third party urls
    path('summernote/', include('django_summernote.urls')),
    
    # built in customized urls
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    
    # custom urls
    path("", include("newspaper1_app.urls")),
    path("api/v1/", include("api_app.urls")),
    
]


if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    
    
handler404 = "newspaper1_app.views.handler404"

api_app/urls.py
from django.urls import include, path
from rest_framework import routers
from api_app import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'posts', views.PostViewSet, basename="posts")
router.register(r'newsletter', views.NewsletterViewSet, basename="newsletter")



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path("post-by-category/<int:cat_id>/", views.PostByCategoryListViewSet.as_view(), name="post-by-category-api",),
    path("post-by-tag/<int:tag_id>/", views.PostByTagListViewSet.as_view(), name="post-by-tag-api",),
    path("draft-list/", views.DraftListViewSet.as_view(), name="draft-list-api",),
    path("post-publish/", views.PostPublishViewSet.as_view(), name="post-publish-api",),
    path("post/<int:post_id>/comments/", views.CommentViewSet.as_view(), name="comments-api",),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'),),
]

newspaper1_app/models.py
from django.db import models

# Create your models here.


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        # by this, table is not created for this model in the database


class Category(TimeStampModel):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(TimeStampModel):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Post(TimeStampModel):
    STATUS_CHOICES = [
        ("active", "Active"),
        ("in_active", "Inactive"),
    ]
    title = models.CharField(max_length=250)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post1_images/%Y/%m/%d", blank=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)

    published_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    views_count = models.PositiveBigIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title
    
    # Fat model and thin views
    @property
    def latest_comments(self):
        comments = Comment.objects.filter(post=self).order_by("-created_at")
        return comments


class Contact(TimeStampModel):
    subject = models.CharField(max_length=200)
    message = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()
    
    def __str__(self):
        return self.subject
    
    
class Newsletter(TimeStampModel):
    email = models.EmailField()
    
    def __str__(self):
        return self.email
    
    
class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    comment = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()
    
    def __str__(self):
        return self.comment[:50]
    
    
    
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    views = models.PositiveIntegerField(default=0)
    # Other fields and methods related to the article model

templates/newsmaster/about.html
{% extends "newsmaster/base.html" %}

{% load static %}

{% block content %}
    <main>
        <!-- About US Start -->
        <div class="about-area">
            <div class="container">
                <!-- Hot Aimated News Tittle-->
                <div class="row">
                    {% comment %} <div class="col-lg-12">
                        <div class="trending-tittle">
                            <strong>Trending now</strong>
                            <!-- <p>Rem ipsum dolor sit amet, consectetur adipisicing elit.</p> -->
                            <div class="trending-animated">
                                <ul id="js-news" class="js-hidden">

                                    {% for post in posts %}
                                    <li class="news-item">
                                        {{ post.title }}
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            
                        </div>
                    </div> {% endcomment %}

 
                </div>
                <div class="row">
                    <div class="col-lg-8">
                        <!-- Trending Tittle -->
                        <div class="about-right mb-90">
                            <div class="about-img">
                                <img src="{% static 'assets/img/post/about_heor.jpg' %}" alt="">
                            </div>
                            <div class="section-tittle mb-30 pt-30">
                                <h3>About Us</h3>
                            </div>
                            <div class="about-prea">
                                <p class="about-pera1 mb-25">
                                    Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                                </p>
                                <p class="about-pera1 mb-25">
                                    Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                                </p>
                                <p class="about-pera1 mb-25">
                                    My hero when I was a kid was my mom. Same for everyone I knew. Moms are untouchable. They’re elegant, smart, beautiful, kind…everything we want to be. At 29 years old, my favorite compliment is being told that I look like my mom. Seeing myself in her image, like this daughter up top, makes me so proud of how far I’ve come, and so thankful for where I come from.
                                    the refractor telescope uses a convex lens to focus the light on the eyepiece.
                                    The reflector telescope has a concave lens which means it bends in. It uses mirrors to focus the image that you eventually see.
                                    Collimation is a term for how well tuned the telescope is to give you a good clear image of what you are looking at. You want your telescope to have good collimation so you are not getting a false image of the celestial body.
                                    Aperture is a fancy word for how big the lens of your telescope is. But it’s an important word because the aperture of the lens is the key to how powerful your telescope is. Magnification has nothing to do with it, its all in the aperture.
                                    Focuser is the housing that keeps the eyepiece of the telescope, or what you will look through, in place. The focuser has to be stable and in good repair for you to have an image you can rely on.
                                    Mount and Wedge. Both of these terms refer to the tripod your telescope sits on. The mount is the actual tripod and the wedge is the device that lets you attach the telescope to the mount.
                                    Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- <div class="col-lg-4">
                        <!-- Section Tittle -->
                        <div class="section-tittle mb-40">
                            <h3>Follow Us</h3>
                        </div>
                        <!-- Flow Socail -->
                        <div class="single-follow mb-45">
                            <div class="single-box">
                                <div class="follow-us d-flex align-items-center">
                                    <div class="follow-social">
                                        <a href="#">
                                            <img src="{% static 'assets/img/news/icon-fb.png' %" alt="">
                                        </a>
                                    </div>
                                    <div class="follow-count">
                                        <span>8,045</span>
                                        <p>Fans</p>
                                    </div>
                                </div>
                                <div class="follow-us d-flex align-items-center">
                                    <div class="follow-social">
                                        <a href="#"><img src="{% static 'assets/img/news/icon-tw.png' %" alt=""></a>
                                    </div>
                                    <div class="follow-count">
                                        <span>8,045</span>
                                        <p>Fans</p>
                                    </div>
                                </div>
                                <div class="follow-us d-flex align-items-center">
                                    <div class="follow-social">
                                        <a href="#"><img src="{% static 'assets/img/news/icon-ins.png' %" alt=""></a>
                                    </div>
                                    <div class="follow-count">
                                        <span>8,045</span>
                                        <p>Fans</p>
                                    </div>
                                </div>
                                <div class="follow-us d-flex align-items-center">
                                    <div class="follow-social">
                                        <a href="#"><img src="{% static 'assets/img/news/icon-yo.png' %" alt=""></a>
                                    </div>
                                    <div class="follow-count">
                                        <span>8,045</span>
                                        <p>Fans</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- New Poster -->
                        <div class="news-poster d-none d-lg-block">
                            <img src="{% static 'assets/img/news/news_card.jpg' %}" alt="">
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
        <!-- About US End -->
    </main>
{% endblock content %}

templates/newsmaster/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>NewsPaper</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
        <link rel="shortcut icon"
              type="image/x-icon"
              href="{% static 'assets/img/favicon.ico' %}">

        <!-- CSS here -->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/ticker-style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        <link rel="stylesheet"
              href="{% static 'assets/css/fontawesome-all.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body>

        {% include "newsmaster/preloader.html" %}

        {% include "newsmaster/header/header.html" %}

        {% block content %}

        {% endblock content %}


        {% include "newsmaster/footer/footer.html" %}



        <!-- Search model Begin -->
        <div class="search-model-box">
            <div class="d-flex align-items-center h-100 justify-content-center">
                <div class="search-close-btn">+</div>
                <form class="search-model-form">
                    <input type="text" id="search-input" placeholder="Searching key.....">
                </form>
            </div>
        </div>
        <!-- Search model end -->

        <!-- JS here -->

        <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
        <!-- Jquery, Popper, Bootstrap -->
        <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
        <!-- Jquery Mobile Menu -->
        <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

        <!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'assets/js/slick.min.js' %}"></script>
        <!-- Date Picker -->
        <script src="{% static 'assets/js/gijgo.min.js' %}"></script>
        <!-- One Page, Animated-HeadLin -->
        <script src="{% static 'assets/js/wow.min.js' %}"></script>
        <script src="{% static 'assets/js/animated.headline.js' %}"></script>
        <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

        <!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'assets/js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
 
        <!-- contact js -->
        <script src="{% static 'assets/js/contact.js' %}"></script>
        <script src="{% static 'assets/js/jquery.form.js' %}"></script>
        <script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'assets/js/mail-script.js' %}"></script>
        <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
 
        <!-- Jquery Plugins, main Jquery -->
        <script src="{% static 'assets/js/plugins.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>
 
        <script>
            $("#newsleter_side_form").submit(function(e) {
                e.preventDefault(); // it makes that prevent from performing default action
                let serializedData = $(this).serialize(); //it converts to understandable form by ajax

                $.ajax({
                    type: "POST",
                    data: serializedData,
                    url: "{% url 'newsletter' %}",
                    success: function(response) {
                        $("#newsletter_side_message").append(`
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <strong>${response.message}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                        `)
                        setTimeout(function() {
                            $('.alert').alert('close');
                        }, 5000)
                        $("newsleter_side_form").trigger("reset")
                    },
                    error: function(response) {
                        $("#newsletter_side_message").append(`
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>${response.responseJSON.message}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                        `)
                        setTimeout(function() {
                            $('.alert').alert('close');
                        }, 5000)
                    },

                })


            })


            $("#newsleter_bottom_form").submit(function(e) {
                e.preventDefault(); // it makes that prevent from performing default action
                let serializedData = $(this).serialize(); //it converts to understandable form by ajax

                $.ajax({
                    type: "POST",
                    data: serializedData,
                    url: "{% url 'newsletter' %}",
                    success: function(response) {
                        $("#newsletter_bottom_message").append(`
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <strong>${response.message}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                        `)
                        setTimeout(function() {
                            $('.alert').alert('close');
                        }, 5000)
                        $("newsleter_bottom_form").trigger("reset")
                    },
                    error: function(response) {
                        $("#newsletter_bottom_message").append(`
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>${response.responseJSON.message}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                        `)
                        setTimeout(function() {
                            $('.alert').alert('close');
                        }, 5000)
                    },

                })


            })
        </script>


        {% block extra_js %}

        {% endblock extra_js %}


    </body>
</html>

templates/newsmaster/contact.html
{% extends "newsmaster/base.html" %}

{% block content %}
    <main>
        <!-- ================ contact section start ================= -->
        <section class="contact-section">
            <div class="container">
 


                <div class="row">
                    <div class="col-12">

                        {% if messages %}
                            {% for message in messages %}
 
 
                                <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                                     role="alert">
                                    <strong>{{ message }}</strong>
                                    {% if form.errors and form.non_field_errors %}{{ form.non_field_errors }}{% endif %}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
 
 
                            {% endfor %}
                        {% endif %}


                        <h2 class="contact-title">Get in Touch</h2>
                    </div>
                    <div class="col-lg-8">
                        <form class="form-contact contact_form"
                              action=""
                              method="post"
                              id="contactForm"
                              novalidate="novalidate">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea class="form-control w-100"
                                                  name="message"
                                                  id="message"
                                                  cols="30"
                                                  rows="9"
                                                  onfocus="this.placeholder = ''"
                                                  onblur="this.placeholder = 'Enter Message'"
                                                  placeholder="Enter Message"></textarea>
                                        {{ form.message.errors }}

                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid"
                                               name="name"
                                               id="name"
                                               type="text"
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Enter your name'"
                                               placeholder="Enter your name">
                                        {{ form.name.errors }}

                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid"
                                               name="email"
                                               id="email"
                                               type="email"
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Enter email address'"
                                               placeholder="Email">
                                        {{ form.email.errors }}

                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <input class="form-control"
                                               name="subject"
                                               id="subject"
                                               type="text"
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Enter Subject'"
                                               placeholder="Enter Subject">
                                        {{ form.subject.errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-3">
                                <button type="submit" class="button button-contactForm boxed-btn">Send</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="media contact-info">
                            <span class="contact-info__icon"><i class="ti-home"></i></span>
                            <div class="media-body">
                                <h3>Buttonwood, California.</h3>
                                <p>Rosemead, CA 91770</p>
                            </div>
                        </div>
                        <div class="media contact-info">
                            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                            <div class="media-body">
                                <h3>+1 253 565 2365</h3>
                                <p>Mon to Fri 9am to 6pm</p>
                            </div>
                        </div>
                        <div class="media contact-info">
                            <span class="contact-info__icon"><i class="ti-email"></i></span>
                            <div class="media-body">
                                <h3>support@colorlib.com</h3>
                                <p>Send us your query anytime!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ================ contact section end ================= -->
    </main>
{% endblock content %}

templates/newsmaster/detail.html
{% extends 'newsmaster/base.html' %}

{% block content %}

    <!--================Blog Area =================-->
    <section class="blog_area single-post-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
 
                    {% include "newsmaster/main/detail/left/post.html" %}

                    {% include "newsmaster/main/detail/left/nav.html" %}
 
                    {% include "newsmaster/main/detail/left/author.html" %}

                    {% include "newsmaster/main/detail/left/comment_list.html" %}

                    {% include "newsmaster/main/detail/left/comment_form.html" %}
 
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">                        
                        
                    {% include "newsmaster/main/detail/right/search.html" %}

                    {% include "newsmaster/main/detail/right/category.html" %}

                    {% include "newsmaster/main/detail/right/popular.html" %}

                    {% include "newsmaster/main/detail/right/tag.html" %}
                        
                    {% include "newsmaster/main/detail/right/newsletter.html" %}

                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ Blog Area end =================-->

{% endblock content %}

templates/newsmaster/home.html
{% extends "newsmaster/base.html" %}

{% block content %}

    <main>
 

        {% include "newsmaster/main/trending.html" %}

        {% include "newsmaster/main/whata_news.html" %}

        
 
        {% include "newsmaster/main/weekly_news.html" %}

        {% include "newsmaster/main/weekly3_news.html" %}
 
        

        

        
 
    </main>
    
        
        

{% endblock content %}

templates/newsmaster/list.html
{% extends "newsmaster/base.html" %}

{% block content %}
    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">

                        {% for post in posts %}
                            <article class="blog_item">
                                <div class="blog_item_img">
                                    <img class="card-img rounded-0" src="{{ post.featured_image.url }}" alt="">
                                    <a href="#" class="blog_item_date">
                                        <h3>{{ post.published_at|date:"d" }}</h3>
                                        <p>{{ post.published_at|date:"M" }}</p>
                                    </a>
                                </div>

                                <div class="blog_details">
                                    <a class="d-inline-block" href="{% url 'post-detail' post.pk %}">
                                        <h2>{{ post.title|truncatechars:44 }}</h2>
                                    </a>
                                    <p>{{ post.content|truncatechars:200|safe }}</p>
                                    <ul class="blog-info-link">
                                        <li>
                                            <a href="#"><i class="fa fa-user"></i> {{ post.tag.all|join:", " }}</a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="fa fa-comments"></i> {{ post.latest_comments.count }} Comments </a>
                                        </li>
                                    </ul>
                                </div>
                            </article>
                        {% endfor %}
 
                        {% include "newsmaster/pagination.html" %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
 
                        {% include "newsmaster/main/detail/right/search.html" %}

                        {% include "newsmaster/main/detail/right/category.html" %}

                        {% include "newsmaster/main/detail/right/popular.html" %}

                        {% include "newsmaster/main/detail/right/tag.html" %}
 
                        {% include "newsmaster/main/detail/right/newsletter.html" %}
 
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock content %}